# Single-package workspace (not a monorepo)
packages: []

ignoredBuiltDependencies:
  - '@playwright/browser-chromium'
  - '@prisma/engines'
  - '@sentry/cli'
  - core-js
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - unix-dgram
  - unrs-resolver
